name: Bug Report
description: Report an issue with the current rules or documentation
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!

  - type: textarea
    id: what-happened
    attributes:
      label: What's the issue?
      description: Describe the problem with the current rules or documentation
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should the rule or documentation say instead?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will help us understand the issue better.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true